version: '3.9'
services:
    redis-0:
      image: redis:5.0
      container_name: redis-0
      volumes:
       - ./redis-0/:/etc/redis
      networks:
          - redis
      expose:
        - 6379
      command: redis-server "/etc/redis/redis.conf"

    redis-1:
      image: redis:5.0
      container_name: redis-1 
      volumes:
          - ./redis-1/:/etc/redis
      networks:
          - redis
      expose:
        - 6379
      command: redis-server "/etc/redis/redis.conf"
      depends_on:
        - redis-0

    sentinel-0:
        image: redis:5.0
        container_name: sentinel-0 
        volumes:
            - ./sentinel-0/:/etc/redis
        networks:
            - redis
        expose:
          - 5000
        command: redis-sentinel "/etc/redis/sentinel.conf"
        depends_on:
          - redis-0    

    sentinel-1:
        image: redis:5.0
        container_name: sentinel-1 
        volumes:
            - ./sentinel-1/:/etc/redis
        networks:
            - redis
        expose:
          - 5000
        command: redis-sentinel "/etc/redis/sentinel.conf"
        depends_on:
          - redis-1   
networks:
    redis: